version: "3.9"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    networks:
      - ai-quiz-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 310s
      retries: 3
    restart: unless-stopped

  quiz-service:
    build: ./services/quiz-service
    ports:
      - "3002:3002"
    networks:
      - ai-quiz-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 310s
      retries: 3
    restart: unless-stopped
  
  results-service:
    build: ./services/result-service
    ports:
      - "3003:3003"
    networks:
      - ai-quiz-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 310s
      retries: 3
    depends_on:
      - quiz-service
networks:
  ai-quiz-net:
    driver: bridge
